Algoritmo "EXERC-H-ENQUANTOMANZANNO"
// Disciplina   : [ Lógica de Programação]
// Professor   :Jailson
// Descrição   : Converter celsius em Fahrenheith
// Autor(a)    : Lavinia
// Data atual  : 22/09/2025
Var
   // Seção de Declarações das variáveis

   F, C:real
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
  C <- 10

   enquanto C <= 100 faca
   F <- (C * 9/5) + 32
   escreval(C, "C°", " = ", "F°", F)
   C <- C + 10
   fimenquanto

Fimalgoritmo