Algoritmo "EXER-C-PARA"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   :
// Autor(a)    : Lavinia
// Data atual  : 27/09/2025
var
    contador: inteiro
    soma: inteiro
inicio
    soma <- 0
    para contador de 1 ate 100 passo 1 faca
        soma <- soma + contador
    fimpara
    escreval("A soma dos 100 primeiros números é: ", soma)
fimalgoritmo