Algoritmo "EXER-B-PARA"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   :
// Autor(a)    : Lavinia
// Data atual  : 27/09/2025
var
    numero: inteiro
    multiplicador: inteiro
inicio
    escreva("Digite o número para ver a tabuada: ")
    leia(numero)

    para multiplicador de 1 ate 10 passo 1 faca
        escreval(numero, " x ", multiplicador, " = ", numero * multiplicador)
    fimpara
fimalgoritmo