Algoritmo "EXER-B-PAG25"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Fahrenheit to Celsius
// Autor(a)    : Lavinia
// Data atual  : 27/09/2025
Var
// Seção de Declarações das variáveis
 C,F:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

escreval("digite a temperatura em graus Fahrenheit: ")
leia(F)

C <- (F - 32) * (9/5)

escreval(F, " f° = ", C, " c°")

Fimalgoritmo