Algoritmo "EXER-A-PAG25"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson 
// Descrição   : Celsius to Fahrenheit
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/09/2025
Var
// Seção de Declarações das variáveis 
 C,F:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("digite a temperatura em graus celsius")
leia(C)

F <- C * (9/5) +32

escreval(C, "c° = ", F, " F°")

Fimalgoritmo