Algoritmo "repita"
// Disciplina   : [ Lógica de Programação]
// Professor   :Jailson
// Descrição   : laço de repetição enquanto
// Autor(a)    : lavinia
// Data atual  : 17/09/2025
Var
   // Seção de Declarações das variáveis
   contador:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   contador<- 1
   repita
      escreval ("Somente a dor coletiva gera união")
      contador<- contador + 1
   até contador >9
Fimalgoritmo